name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node v20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Enable Corepack
      run: corepack enable
    - name: Install dependencies
      run: yarn install --immutable
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Build Files
      run: yarn build
    - name: Run Playwright tests
      run: yarn test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
